name: jackettio
services:

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
    networks:
      - jackettio
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    depends_on:
      - flaresolverr
    networks:
      - jackettio
    restart: unless-stopped
    volumes:
      - jackett-config:/config
      - jackett-downloads:/downloads
    ports:
      - 9117:9117

  jackettio:
    image: todo
    container_name: jackettio
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - DATA_FOLDER=/data
    depends_on:
      - jackett
    networks:
      - jackettio
    ports:
      - 4000:4000
    restart: unless-stopped
    volumes:
      - ./src:/home/node/app/src
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackettio.entrypoints=web,websecure"
      - "traefik.http.routers.jackettio.rule=Host(`${ACME_DOMAIN:-}`)"
      - "traefik.http.routers.jackettio.tls=true"
      - "traefik.http.routers.jackettio.tls.certresolver=letsencryptresolver"
    
networks:
  jackettio:

volumes:
  jackett-config:
  jackett-downloads: